import com.badlogic.gdx.tools.texturepacker.TexturePacker

buildscript {
  repositories {
    mavenCentral()
  }

  dependencies {
    classpath "com.badlogicgames.gdx:gdx-tools:1.14.2"
  }
}

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.github.libgdx:box2dlights:$box2dlightsVersion"
  api "com.badlogicgames.gdx-controllers:gdx-controllers-core:$gdxControllersVersion"
  api "com.badlogicgames.gdx:gdx-ai:$aiVersion"
  api "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.github.tommyettinger:libgdx-texturepacker:$texturePackerOnlyVersion"
  api "com.github.tommyettinger:regexodus:$regExodusVersion"
  api "com.github.tommyettinger:textratypist:$textratypistVersion"

  api "com.github.tommyettinger.gdx-utils:libgdx-utils:$utilsVersion" // JitPack commits

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

var packTextures = tasks.register("packTextures") {
  var inputDir = "$rootDir/assets/images/included"
  var outputDir = "$rootDir/assets/images/included/packed"
  inputs.dir(inputDir)
  outputs.dir(outputDir)
  doLast {
    delete(outputDir)
    var settings = new TexturePacker.Settings()
    settings.maxWidth = 4096
    settings.maxHeight = 4096
    settings.combineSubdirectories = true
    TexturePacker.process(settings, inputDir, outputDir, "images.pack")
  }
}
